### ISSUE TITLE
[BUG] `podman` does not support the `uid` argument for a tmpfs volume mount

### ISSUE THREAD

**Issue by sbuerk** [FriendsOfTYPO3/tea#1087] opened 2023-12-19 09:15 UTC
The TYPO3 core `runTests.sh` has been using the
`uid` option for the `tmpfs` mount in the past
and removed it due to the fact it's not supported
by the `podman` container binary.

This has been missed to change along with the
introduction of the `-b` container binary option
and therefore the podmand and docker dual support.

For example, following

```shell
--tmpfs ${ROOT_DIR}/typo3temp/var/tests/functional-sqlite-dbs/:rw,noexec,nosuid,uid=${HOST_UID}
```

should be changed to

```shell
--tmpfs ${ROOT_DIR}/typo3temp/var/tests/functional-sqlite-dbs/:rw,noexec,nosuid
```

which works for both binaries in case of tmpfs mounts

**Comment by oliverklee** [comment] 2023-12-19 09:20
Possibly a duplicate of or related to #1083?

**Comment by sbuerk** [comment] 2023-12-19 09:22
yes - not saw that issue, sorry for the double issue.

**Closed** 2023-12-19 09:37 UTC
Labels: bug, make switch to runTests.sh
